sudo: required

services:
    - docker

language: generic

before_install:
    - docker build -t geosony/docker-react -f Dockerfile.dev .

script:
    - docker run -e CI=true geosony/docker-react npm run test

