sudo: required

services:
    - docker

language: generic

before_install:
    - docker build -t geosony/docker-react -f Dockerfile.dev .

script:
    - docker run -e CI=true geosony/docker-react npm run test

deploy:
    provider: elasticbeanstalk
    region: "us-west-2"
    app: "first-deploy"
    env: "FirstDeploy-env"
    bucket_name: "elasticbeanstalk-us-west-2-304191806274"
    bucket_path: "first-deploy"
    on:
        branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key:
        secure: "$AWS_SECRET_KEY"

